### ISSUE TITLE
Wrong date display

### ISSUE THREAD

**Issue by alikhosravidev** [IamRezaMousavi/persian-gnome-calendar-extension#13]
The extension displays the current month incorrectly when date format is yyyy-mm-d
![image](https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/assets/49164621/62edc72a-5af2-4b9d-b3a7-7953fd8b7b02)

**Comment by IamRezaMousavi** [comment]
Thank you for reporting
Working on it

**Comment by alikhosravidev** [comment]
Thank you
