### ISSUE TITLE
Option to change weekdays to Persian

### ISSUE THREAD

**Issue by medicamin** [IamRezaMousavi/persian-gnome-calendar-extension#18]
Hi there,
weekdays are in English ( S, M, T, W, T, F, ). Also numbers are in English.
It would be nice if you add an option to change those to Persian alphabet and digits.
Thanks

**Comment by IamRezaMousavi** [comment]
This is awesome, would you like to work on it?

**Comment by medicamin** [comment]
Unfortunately I'm not a developper and I don't have the knowledge.
I wish I could...

**Comment by IamRezaMousavi** [comment]
You can use this feature now by building from source or wait for the next release
