### ISSUE TITLE
Where's the POT?

### ISSUE THREAD

**Issue by avds2** [IamRezaMousavi/persian-gnome-calendar-extension#30]
خودت که زبونت فارسیه و برای فارسی‌زبان‌ها نوشتی این تقویم «فارسی» رو، زبون فارسی اضافه نکردی :)
اقلاً POT بده من فارسیش کنم.

**Comment by IamRezaMousavi** [comment]
با سلام و احترام
دایرکتوری [po](https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/tree/master/persian-calendar%40iamrezamousavi.gmail.com%2Fpo) چک شود
(مطمئنا متوجه خواهید شد که نیاز است در کد تغییراتی لحاظ شود تا متون استخراج شوند)
