### ISSUE TITLE
date numbers does not follow system locale

### ISSUE THREAD

**Issue by danialbehzadi** [IamRezaMousavi/persian-gnome-calendar-extension#9]
in fa_IR locale, numbers in the calendar are in Latin, despite the GNOME calendar itself follows the system locale and is in Persian.

**Comment by IamRezaMousavi** [comment]
Can you show me a screenshot?

**Comment by danialbehzadi** [comment]
Of course.

extension: 
![نماگرفت از 2023-05-21 17-51-56](https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/assets/3658678/80fdeabf-f906-439e-8ca9-555b30e26d98)

GNOME:

![نماگرفت از 2023-05-21 17-52-15](https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/assets/3658678/94fa5e9b-6bed-4d08-b003-46014357d09b)

**Comment by IamRezaMousavi** [comment]
It's done in 8ac3bdc8f203d1bd92d3b2249af6481572ea0d68 (version 9)
Thank you for reporting


![نماگرفت از 2023-05-22 16-07-04](https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/assets/83984878/f2f75cab-296d-4a2f-be2f-54f183ad4006)
